name: StepCI for SWAPI
on: [push, pull_request, workflow_dispatch]

jobs:
  stepci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workflow:
          - tests/swapi-characters-list.yml
          - tests/swapi-characters-by-id.yml
    steps:
      - uses: actions/checkout@v4
      - name: stepci ${{ matrix.workflow }}
        uses: stepci/stepci@2.8.2
        with:
          workflow: ${{ matrix.workflow }}
        env:
          STEPCI_DISABLE_ANALYTICS: "1"

